config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests

  patch "cat_rental_requests/:id/approve", to: "cat_rental_requests#approve", as: 'approve'
  patch "cat_rental_requests/:id/deny", to: "cat_rental_requests#deny", as: 'deny'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = %w(white black gray orange brown)
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color" }, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex" }, presence: true
  validates :name, :birth_date, :description, presence: true

  has_many :cat_rental_requests
  
  def age
    Date.today.year - birth_date.year
    # time_ago_in_words(birth_date)
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUSES = %w(PENDING APPROVED DENIED)
  attribute :status, :string, default: 'PENDING'
  validates :status, inclusion: { in: STATUSES,
    message: "%{value} is not a valid status" }, presence: true
  validates :cat_id, :start_date, :end_date, presence: true

  belongs_to :cat,
  dependent: :destroy

  def overlapping_requests
    self.class
      .select("*")
      .where("( start_date <= ? AND ? <= end_date )
      OR (start_date <= ? AND ? <= end_date )
      OR (start_date >= ? AND ? >= end_date )",
        self.start_date, self.start_date, self.end_date, self.end_date, self.start_date, self.end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_request
    !overlapping_approved_requests.exists?
  end

  def approve!
    if self.status != 'PENDING'
      self.errors[:base] << "status is not PENDING"
      return false
    end
    self.class.transaction do
      self.update_column(:status, 'APPROVED')
      overlapping_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    if self.status != 'PENDING'
      self.errors[:base] << "status is not PENDING"
      return false
    end
    self.update_column(:status, 'DENIED')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if !@request.does_not_overlap_approved_request
      @request.errors[:base] << "Overlaps approved request"
      render plain: @request.errors.full_messages
    elsif @request.save
      redirect_to cat_url(@request.cat)
    else
      render plain: @request.errors.full_messages
      # render :new
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    if @request.approve!
      redirect_to cat_url(@request.cat)
    else
      render plain: @request.errors.full_messages
    end
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    if @request.deny!
      redirect_to cat_url(@request.cat)
    else
      render plain: @request.errors.full_messages
    end
  end

  private

  def request_params
    params.require(:request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render plain: @cat.errors.full_messages
      # render :new
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<% action_url = cat_rental_requests_url %>
<h1>Book a Cat!</h1>
<form action="<%= action_url %>" method="post">
  <label for="start_date">Start Date</label>
  <br>
  <input type="date" name="request[start_date]" value="">
  <br>
  <label for="end_date">End Date</label>
  <br>
  <input type="date" name="request[end_date]" value="">
  <br>

  <label for="Cat">Cat</label>
  <select id="cat" name="request[cat_id]">
    <option disabled selected>-- Please Select --</option>

    <% cats = Cat.all %>
    <% cats.each do |cat| %>
      <option value="<%=cat.id%>"><%=cat.name%></option>
    <% end %>

  </select>
  <br>
  <input type="submit" value="Submit Booking Request">

</form>

app/views/cats/_cat.html.erb
<li>
  <%= cat.name %>
</li>

app/views/cats/_form.html.erb
<!-- <%# if action == :edit %> -->
<% if cat.persisted? %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  <br>

  <label for="sex">Sex</label> <br>

  <input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>> M <br>
  <input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>> F <br>


  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected"%>>-- Please Select --</option>
    <option value="<%=Cat::COLORS[0]%>" <%= cat.color == Cat::COLORS[0] ? "selected" : "" %>><%=Cat::COLORS[0] %></option>
    <option value="<%=Cat::COLORS[1]%>" <%= cat.color == Cat::COLORS[1] ? "selected" : "" %>><%=Cat::COLORS[1] %></option>
    <option value="<%=Cat::COLORS[2]%>" <%= cat.color == Cat::COLORS[2] ? "selected" : "" %>><%=Cat::COLORS[2] %></option>
    <option value="<%=Cat::COLORS[3]%>" <%= cat.color == Cat::COLORS[3] ? "selected" : "" %>><%=Cat::COLORS[3] %></option>
    <option value="<%=Cat::COLORS[4]%>" <%= cat.color == Cat::COLORS[4] ? "selected" : "" %>><%=Cat::COLORS[4] %></option>
  </select>

  <br>

  <label for=""></label>
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]"><%= cat.description %></textarea>
  <br>
  <input type="submit" value="<%= cat.persisted? ? 'update cat' : 'add cat' %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit cat!</h1>


<%= render 'form', action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<h1>99 Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <%= render cat %>
    <%= link_to "#{cat.name}", cat_url(cat) %>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Add cat to website!</h1>


<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>Age</td>
    <td><%= @cat.age %></td>
  </tr>
  <tr>
    <td>Birthdate</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>Color</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Sex</td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<p>
  <%= @cat.description %>
</p>

<h3>Bookings</h3>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% requests = @cat.cat_rental_requests %>
  <% requests.order(:start_date).each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.status %></td>
    <% if request.status == 'PENDING' %>
      <td> <%= button_to "Approve", approve_url(request), method: :patch %> </td>
      <td> <%= button_to "Deny", deny_url(request), method: :patch %> </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>